### ISSUE TITLE
Let's see the ideal results!

### ISSUE THREAD

**Issue by WeiFoo** [ai-se/TuneData#7]
# What's the best results we can get?

Before we get started, we'd better know where the destination is!
**ARE THEY ALL 100?**

Using the following experiments to find our best results! 
- EXP1:  using testing data as **tuning data**!
- EXP2:  using testing data as both **training data and tuning data**!

**Comment by timm** [comment]
?

**Comment by WeiFoo** [comment]
# EXP1 (use testing data as tuning data )results:

## Precision:

![screen shot 2016-05-04 at 10 30 05 am](https://cloud.githubusercontent.com/assets/7039841/15017359/461ea096-11e3-11e6-9256-32cb4cd19b78.png)

## F:

![screen shot 2016-05-04 at 10 30 15 am](https://cloud.githubusercontent.com/assets/7039841/15017348/3b4e74fc-11e3-11e6-9c0b-e742a81a6fff.png)

# EXP2(use testing as training and tuning data) results:

## Precision:

![screen shot 2016-05-04 at 10 24 43 am](https://cloud.githubusercontent.com/assets/7039841/15017166/7701aae2-11e2-11e6-96dd-8ca363d8884b.png)

## F:

![screen shot 2016-05-04 at 10 23 51 am](https://cloud.githubusercontent.com/assets/7039841/15017132/58cd9d60-11e2-11e6-913d-b3d98feecab3.png)

**Comment by WeiFoo** [comment]
# Comments:
- Even though we're cheating, we should find relevant data in both training and tuning data sets. Only relevant tuning data is not enough.

**Comment by timm** [comment]
remember to redo these with self test on untuned/RF and CART
